### ISSUE TITLE
Business Details - General Details: There is a mobile number added but it doesn't exist from the design 11-WON-contact.psd, can you please show it in the front-end?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#101]
![image](https://cloud.githubusercontent.com/assets/13363508/14665592/c3a3c4fc-0706-11e6-8845-02f6ebec3d74.png)
siness

**Comment by euveng** [comment]
This involves a change in design since the map may be moved downwards. Please mark this for post-live development instead.
