### ISSUE TITLE
Contact Us: Google map should be bottom aligned with the text box area in its left.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#102]
![image](https://cloud.githubusercontent.com/assets/13363508/14665839/9a06c444-0708-11e6-855d-eeb8ddab9fdf.png)

**Comment by euveng** [comment]
The map was originally in line with the Message field, but somehow, someone had added the 'Site address' field, and that moved the Message field down. Will not fix.

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/14879508/465a3902-0d5c-11e6-8e61-9b22ecf78be6.png)

Please look closer the google map height it is shorter than the design, changing the address I believes won't change the UI coz it will only update under Admin -> Business Details.

**Comment by euveng** [comment]
There was a design change after the site was completed - someone added the 'site address', a 5th field in the form. This is the contact form, the form that is on the left side of the screen. That is what pushed the 'message' field down. As a result, the map looks higher than the design. Will not fix this.
