### ISSUE TITLE
Business Details - Social Media: Can you please give me an explanation why you created another field for youtube when you can reuse the existing one?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#103]
![image](https://cloud.githubusercontent.com/assets/13363508/14665914/ffbb3b12-0708-11e6-98ea-98ab8ee29b61.png)

**Comment by euveng** [comment]
1 reason:

The standard Youtube field links to the Youtube page itself. The 2nd Youtube field links to the specific video that loads in the Fancybox in the leadin. If you enter a youtube page URL in the standard Youtube field, it will appear as a social media icon in the header.

**Comment by maehtitan** [comment]
But it is not mentioned in the scope to implement the other field for the fancybox box pop up in the leadin. 

We usually reuse the existing YouTube field and if there is another additional icon for the youtube channel it will be for post-live development instead since it is not shown in the design that there is a Youtube icon.

**Comment by euveng** [comment]
Ok, fixed.

**Comment by maehtitan** [comment]
Please remove the Youtube icon in the top header since it is not shown in the design. And please remove the youtube-featured-video field added.

**Comment by euveng** [comment]
Fixed.
