### ISSUE TITLE
Sidebar Form & Banner Form: Incorrect font-size used in placeholder.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#113]
![image](https://cloud.githubusercontent.com/assets/13363508/14696407/63d4e180-07ad-11e6-9756-0f9d96945e9a.png)

![image](https://cloud.githubusercontent.com/assets/13363508/14696726/1694ffb0-07b0-11e6-853d-6a2b2b8ec56c.png)

**Comment by euveng** [comment]
Fixed.
