### ISSUE TITLE
Homepage - Leadins: There is a content mentioned in the scope but it doesn't shown as per scope. I believe this is scope error.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#118]
![image](https://cloud.githubusercontent.com/assets/13363508/14699184/38b3f7c8-07c8-11e6-8bf9-6950c7e7e240.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14699206/6c67c46e-07c8-11e6-9815-df7846fb1114.png)

**Comment by euveng** [comment]
Yes, scope error.
