### ISSUE TITLE
General - Header: Font-size isn't consistent for all main page content.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#119]
![image](https://cloud.githubusercontent.com/assets/13363508/14700049/6a0431ce-07cf-11e6-947d-533a8d0c01f1.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14700100/ab9a7a6c-07cf-11e6-8b7b-237724dfb156.png)

**Comment by euveng** [comment]
I'm just following design

**Comment by maehtitan** [comment]
But it is mentioned in the scope to make it consistent.
![image](https://cloud.githubusercontent.com/assets/13363508/14906610/e9f421fc-0def-11e6-92de-4b1a74605227.png)

**Comment by euveng** [comment]
That is a general guideline, so design will override it.
