### ISSUE TITLE
Leadins, Why Choose Us & Testimonials Section: Please add in the field instruction for the image size dimension to be uploaded.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#120]
![image](https://cloud.githubusercontent.com/assets/13363508/14700476/6ce6f770-07d2-11e6-8aaf-22e298fbce92.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14700485/7c454ef6-07d2-11e6-884d-298922057338.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14700496/86827722-07d2-11e6-836d-0e186896d718.png)

**Comment by euveng** [comment]
Fixed.
