### ISSUE TITLE
Homepage - Client Testimonials: It must be limit to 4 post items only as per design and scope. I believe in the scope it states per post item not per page since it is located in the homepage and not in testimonials page.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#124]
![image](https://cloud.githubusercontent.com/assets/13363508/14703184/2769aa12-07e1-11e6-90fe-4f1998edc155.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14703222/63167428-07e1-11e6-8caf-e70d27ffd39f.png)

**Comment by euveng** [comment]
Fixed.
