### ISSUE TITLE
Heading font-sizes: Where did you get your font-size from <h2> since as per design no <h2> header mentioned under "About Us" page and if no other header mentioned we should follow the <h1>.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#126]
![image](https://cloud.githubusercontent.com/assets/13363508/14703693/da8d7414-07e3-11e6-98fc-b8942cc635ed.png)

**Comment by euveng** [comment]
Is there a standard in the knowledge base for this?

**Comment by roseliesromeo** [comment]
Seli:
https://knowledgebase.titanweb.com.au/implementation/standard-pages/page-content-styling
![image](https://cloud.githubusercontent.com/assets/11186313/14907021/6208100e-0df5-11e6-8b55-9fa7f89b02a7.png)

**Comment by euveng** [comment]
Ok, which H1 should we follow? Homepage H1 is 30px and inner page H1 is 32px.

**Comment by maehtitan** [comment]
It's up to you as long as it will not destroy the layout alignment. Thanks

**Comment by euveng** [comment]
I would prefer that you suggest the sizes so I don't have to fix it again in case a different outcome was expected.

**Comment by maehtitan** [comment]
We must follow the <h1> in homepage which has 30px font-size which turns to 28px in <h2>, if we follow the <h1> in the Inner page which has 32px font-size, it will turn to 30px as <h2> which has the same font-size in the homepage <h1>.

**Comment by euveng** [comment]
Fixed.
