### ISSUE TITLE
Testimonials: No default no-image reflected. It is mentioned in the scope to not show the images only if no image found from the design for all post.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#127]
Since there are images found from the design, then showed the default no-image.

![image](https://cloud.githubusercontent.com/assets/13363508/14704460/61622d7e-07e7-11e6-9c45-cc80ab1f6045.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14704478/7b7d5bac-07e7-11e6-86bc-d4b5035abdeb.png)

**Comment by euveng** [comment]
I don't understand this issue, can you rewrite it please.

**Comment by maehtitan** [comment]
As per scope mentioned, default to use placeholder image if no featured image is uploaded, right? Why no default no-image found from the Testimonials when I found featured images from the design?

**Comment by euveng** [comment]
Fixed.
