### ISSUE TITLE
Gallery: Images thumbnail must have border-radius as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#129]
![image](https://cloud.githubusercontent.com/assets/13363508/14772098/812b338e-0acc-11e6-820e-7a71ae3359ce.png)

**Comment by maehtitan** [comment]
Please apply fix to other pages which needs border-radius like the Product, Versatility and Installation page

**Comment by euveng** [comment]
Fixed.
