### ISSUE TITLE
Mobile - banner: Banner description is overlapping with navigation icon's on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#13]
Samsung E7, Ipod, Ipad mini & Ipad air

Portrait
![screenshot_2016-03-09-11-50-15](https://cloud.githubusercontent.com/assets/13309730/13634111/81f0f3f8-e619-11e5-9b4e-e254cd2b4d8f.png)

Landscape
![screenshot_2016-03-09-11-50-26](https://cloud.githubusercontent.com/assets/13309730/13634134/9f37694c-e619-11e5-87f9-74a5be234000.png)

**Comment by euveng** [comment]
Fixed

**Comment by mahender-sowedane** [comment]
Still affected on resolutions 1024(Ipad mini-Landscape view) & 1200.

![2016-03-10_1617](https://cloud.githubusercontent.com/assets/13309730/13667362/fbe20ab8-e6db-11e5-9ef7-e5355c170714.png)

**Comment by euveng** [comment]
Fixed for the specified resolutions.
