### ISSUE TITLE
Versatility, Gallery & Installation: Not all thumbnail images are cleared some are blurry, not just in desktop view but to all view port size.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#130]
![image](https://cloud.githubusercontent.com/assets/13363508/14772113/d38682b4-0acc-11e6-9c27-34fc6cd29c2b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14772255/a1849f38-0ace-11e6-8103-1f33029f156f.png)

Installation: 
![image](https://cloud.githubusercontent.com/assets/13363508/14772810/f2a743a6-0ad4-11e6-9c25-1f292e63bc6c.png)

Versatility:
![image](https://cloud.githubusercontent.com/assets/13363508/14772826/13935ca8-0ad5-11e6-9854-aa66849b0d02.png)

**Comment by euveng** [comment]
Looks fine to me. Try uploading higher res images.
![image](https://cloud.githubusercontent.com/assets/9030354/14907158/65202a54-0df7-11e6-9ca2-0b556ef650a9.png)

**Comment by maehtitan** [comment]
All images are high res when opening in the pop up fancy box it will only blur seeing it in the thumbnail.

**Comment by euveng** [comment]
I've just replaced those images with higher res ones, can you check now?

**Comment by maehtitan** [comment]
Not all are fixed. Please refer to this galleries http://luxuride.stage.titanweb.com.au/galleries/, If you have seen the images display are fully reponsive and no pixelated images found.

**Comment by euveng** [comment]
Unable to reproduce this. Again, if you can indicate the specific images that would speed things up. It could be due to the uploaded image quality and not a development issue.
