### ISSUE TITLE
Product: Images are broken.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#132]
![image](https://cloud.githubusercontent.com/assets/13363508/14772504/cebb66e6-0ad1-11e6-99f4-ddf2f53c9720.png)

**Comment by euveng** [comment]
Unable to produce this. Perhaps try deleting the images and reuploading from your end and retest.

**Comment by maehtitan** [comment]
Try to check the staging images not in your local you can see most images aren't displaying, I don't have these images because I believe they are the final content.

**Comment by euveng** [comment]
We don't have the final images either. Perhaps the uploader performed the upload wrongly. I've just uploaded some test images and they are fine.
