### ISSUE TITLE
News listing: Images are too big in 991px view port size and below, please retain what is it implemented in desktop view coz viewing in the full image width can be seen in the single page only.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#141]
![image](https://cloud.githubusercontent.com/assets/13363508/14773245/51d4a940-0ada-11e6-85d9-2fea9a5b9aea.png)

Currently in ipad view Listing view, images are big and when opening it in a single view it is too small.
![image](https://cloud.githubusercontent.com/assets/13363508/14773378/f632a1bc-0adb-11e6-911f-8d20dba899f6.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14773383/0489e996-0adc-11e6-8c0c-7d8eba02a88c.png)

**Comment by euveng** [comment]
Fixed to show smaller thumbnail until 768px.

**Comment by maehtitan** [comment]
Please also retain the image size dimension in 767px view port size and below just like this image below
![image](https://cloud.githubusercontent.com/assets/13363508/14951265/4f8c06c8-108a-11e6-90db-f8f8fc076bba.png)


Current image are still big seems it's not a listing images anymore
![image](https://cloud.githubusercontent.com/assets/13363508/14951274/6d63fdd6-108a-11e6-9d6d-5e001a0e844d.png)

**Comment by euveng** [comment]
Fixed.
