### ISSUE TITLE
Contact Us: Message text box area doesn't have validation message.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#143]
![image](https://cloud.githubusercontent.com/assets/13363508/14947740/64b2b120-106a-11e6-8ba1-cfba024c8a20.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14948302/3ed3b9d4-1071-11e6-931f-151ad5fdfc73.png)

**Comment by euveng** [comment]
Fixed.
