### ISSUE TITLE
Header Section: Burger menu background height isn't consistent in 320px - 767px viewport size & 768px - 992px viewport size.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#144]
768px - 992px viewport size - height layout is shorter than the 320px - 767px viewport size which causes the burger menu in 768-992px view port size isn't aligned at the middle vertically
![image](https://cloud.githubusercontent.com/assets/13363508/14948572/9f386042-1074-11e6-87dd-53ac56d3226f.png)

**Comment by euveng** [comment]
Fixed.
