### ISSUE TITLE
News Single: Please achieve the image size dimension as per design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#146]
![image](https://cloud.githubusercontent.com/assets/13363508/14950518/c7ce5876-1084-11e6-8236-05c053c09112.png)

**Comment by euveng** [comment]
If you are not yet aware by now, we are using Bootstrap for our sites. Bootstrap is a frontend framework that comes with CSS classes for developing responsive, mobile first projects on the web. The column that the featured image sits in has a class of col-sm-4 which means that it has a 33.33% width. This means that sometimes, the designs may deviate slightly from the bootstrap classes. This has been discussed before and I am surprised that this is flagged again.
