### ISSUE TITLE
Homepage Form - Mobile and Responsive View: Video overlapped the form in 320px - 767px view port size.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#147]
![image](https://cloud.githubusercontent.com/assets/13363508/14950771/d5c8c7b6-1086-11e6-91d0-b0c72a00bf99.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14950796/fb33ce24-1086-11e6-8968-1d80641c72be.png)

**Comment by euveng** [comment]
Fixed.
