### ISSUE TITLE
Banner Section: Banner should be paused on hover when there are text contents and button added.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#149]

**Comment by euveng** [comment]
Discussed in #30

**Comment by roseliesromeo** [comment]
This has been part of our checking. This has recently been added in our standard implementation. 
https://knowledgebase.titanweb.com.au/development-2016/development-modules-development-2016/banners

**Comment by euveng** [comment]
Fixed.
