### ISSUE TITLE
Banner form - Inner pages Gravity form: Form is overlapping when more description added, It should be as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#18]
![2016-03-09_1835](https://cloud.githubusercontent.com/assets/13309730/13636106/032f9cc4-e626-11e5-8ef0-57c60bf22e50.png)

**Comment by euveng** [comment]
The output from gravity form cannot be manipulated with, so I have applied a css solution to set maximum-height: 70px and overflow:hidden.
