### ISSUE TITLE
Footer menu should be aligned properly as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#20]
![untitled-1-ftr01](https://cloud.githubusercontent.com/assets/13309730/13636611/c80c914e-e628-11e5-807e-2e78d52c8773.png)

**Comment by euveng** [comment]
The homepage was missing row classes in wrapper sections so they had an extra 15px horizontal padding. I have fixed this and they are now in line with the footer menu.

**Comment by mahender-sowedane** [comment]
Still some of the items are out of the line, It should be as per design

![untitled-1-homee](https://cloud.githubusercontent.com/assets/13309730/13665614/633475d8-e6d3-11e5-8125-2e5b63947381.png)

**Comment by euveng** [comment]
it should look like this now. 
![image](https://cloud.githubusercontent.com/assets/9030354/13690749/18556eaa-e76e-11e5-8f5b-39693808270b.png)
