### ISSUE TITLE
W3C - Home page: 10 Errors, 3 Warnings.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#23]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2F

![2016-03-09_1923-hm](https://cloud.githubusercontent.com/assets/13309730/13637276/7b8ede5e-e62c-11e5-82b9-1d913cd4dd68.png)

**Comment by euveng** [comment]
Fixed.
