### ISSUE TITLE
W3C - Testimonials page: 4 Errors, 3 Warnings.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#24]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2Ftestimonials%2F

![2016-03-09_1928-test](https://cloud.githubusercontent.com/assets/13309730/13637399/237b0782-e62d-11e5-99b4-8c371c2e4ca8.png)

**Comment by euveng** [comment]
Fixed.
