### ISSUE TITLE
W3C - Installation page: 1 Error.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#25]
Same issue affected on FAQ's page also.

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2Finstallation%2F

![2016-03-09_1929-insta](https://cloud.githubusercontent.com/assets/13309730/13637441/5d250d98-e62d-11e5-95a5-f7c5185bbc62.png)

**Comment by euveng** [comment]
Fixed.
