### ISSUE TITLE
Mobile : 'Contact Us' form should be aligned center on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#27]
Ipod (L), Samsung E7(L), Ipad mini(P&L) views.

![screenshot_2016-03-09-15-13-46](https://cloud.githubusercontent.com/assets/13309730/13637984/27dbf400-e630-11e5-904a-e3c66d01a63e.png)

**Comment by euveng** [comment]
Please provide the URL as well for issues like these. I am unable to reproduce this issue.

**Comment by mahender-sowedane** [comment]
'http://wonderwalls.stage.titanweb.com.au/about/'
Affected on single pages.
also reproduced on browser reflow, have a look below screen
thanks!

![2016-03-10_1251-ff](https://cloud.githubusercontent.com/assets/13309730/13662209/e398b05a-e6be-11e5-930a-f368484777c4.png)

**Comment by euveng** [comment]
Unable to reproduce as suggested. Please see snapshot of all our testing devices.
![img_20160310_162307](https://cloud.githubusercontent.com/assets/9030354/13663451/b14839c2-e6dc-11e5-901b-1e7dde5f366a.jpg)

**Comment by mahender-sowedane** [comment]
Yes,previously working fine in devices but see my comments above this issue re-produced on browser reflow. It's working fine now.
But now form is enlarging on re-flow, previously not
have a look below screen.
thanks!
![2016-03-14_1208-01](https://cloud.githubusercontent.com/assets/13309730/13736809/e7b7bf38-e9dd-11e5-8e03-4e040442d763.png)
