### ISSUE TITLE
Admin-Banner: Unable to add intro text since WYSIWYG editor is not enabled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#28]
![2016-03-09_1737-bnr](https://cloud.githubusercontent.com/assets/13309730/13639879/bb0777ce-e638-11e5-9e61-05bf9e2257e3.png)

**Comment by euveng** [comment]
Unable to reproduce error, content editor is available for banner custom posts.

**Comment by mahender-sowedane** [comment]
I'm aware of that, Have a look above screenshot that's also banner custom post. while testing It happens for newly added banners, but it's working fine now.
Thanks!
