### ISSUE TITLE
Header-Menu: Some of the items are missing in header menu, It should be as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#29]
![untitled-1-header](https://cloud.githubusercontent.com/assets/13309730/13664557/1221b6ce-e6ce-11e5-9128-9046a872c72f.png)

**Comment by euveng** [comment]
it was there before, I don't know who removed it. it's back now.

**Comment by mahender-sowedane** [comment]
Yes, it was there when i tested first time. have a look  #9 issue screenshot news page is there, But when I'm performing testing on 2nd time i have found this issue. I also don't know who removed
how would i know, It's not invalid. but now it's fine.
Thanks!
