### ISSUE TITLE
Banner form: Banner form is overlapping when you click on 'Submit' button with empty fields

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#3]
Also error messages should be align proper, currently getting confusion which error message is indicating to which field..

![2016-03-09_1430-bannerform01](https://cloud.githubusercontent.com/assets/13309730/13630527/bdbce644-e605-11e5-8f93-730202864711.png)

**Comment by euveng** [comment]
Fixed
