### ISSUE TITLE
News page: Not enough space between the page title and post title, image and description respectively.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#35]
It should be as per design.

![untitled-1-newssss](https://cloud.githubusercontent.com/assets/13309730/13670388/a95309b4-e6ef-11e5-97a4-f1ec27b06868.png)

**Comment by euveng** [comment]
#1 - The featured images follow bootstrap column classes, we are allowed some flexibility here.
#2 - Fixed.
