### ISSUE TITLE
Home-Our Major Clients: Logos are overlapping with each other, As per design only 4 logos should be displayed.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#36]
![untitled-1-logos](https://cloud.githubusercontent.com/assets/13309730/13670990/301630d6-e6f3-11e5-923c-9b683e33b59b.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
As per design logo's should be 4 only

![2016-03-14_1544](https://cloud.githubusercontent.com/assets/13309730/13741354/c9bec756-e9fb-11e5-9bbe-79dea6e089d1.png)

**Comment by euveng** [comment]
Fixed.
