### ISSUE TITLE
Home - Client Testimonials: Overlay is getting distorted, It should be align properly as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#4]
![2016-03-09_1448-overlay](https://cloud.githubusercontent.com/assets/13309730/13630618/440fa164-e606-11e5-8e2c-aa184d96dd7d.png)

**Comment by euveng** [comment]
Unable to reproduce, can you advise steps to reproduce this?

**Comment by mahender-sowedane** [comment]
Yes, move the cursor to anyone  of the testimonial you will get hover image.
thanks!

**Comment by euveng** [comment]
Ok, I have applied a fix, please check.

**Comment by mahender-sowedane** [comment]
Fixed
