### ISSUE TITLE
General pages: Style of the pagination isn't implemented as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#40]
![untitled-1-pagin](https://cloud.githubusercontent.com/assets/13309730/13671634/029378a4-e6f7-11e5-8ba3-3cabadbf7602.png)

**Comment by euveng** [comment]
Our new standards use Bootstrap pagination, which does not generate the 'first and last page' links. Design has accepted this and has started implementing this in all designs.

Assuming that this is the only issue, I will mark this as wontfix.

**Comment by mahender-sowedane** [comment]
I didn't get any update from my TL regarding this issue, So kindly take the reference below specified
Url 'http://sunlite.stage.titanweb.com.au/projects/' and fix it properly.
Thanks!
Reference screenshot
![2016-03-14_1851-ref](https://cloud.githubusercontent.com/assets/13309730/13745811/160b95f2-ea16-11e5-93b3-07cb5e0710e4.png)

**Comment by euveng** [comment]
Discussed with Jo and we will not implement first and last links within pagination. We will send out the new standards in time.

Marking this as will not fix.
