### ISSUE TITLE
FAQ: Not all posts are displayed in front end. Created 16 posts for Faq but only 10 are displayed.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#42]
Which posts are displaying in back-end, they aren't reflected to front-end.

![untitled-1-faq01](https://cloud.githubusercontent.com/assets/13309730/13672232/ec811e06-e6f9-11e5-82e0-279631994e02.png)

**Comment by euveng** [comment]
Fixed.
