### ISSUE TITLE
News page: When the post titles are single line layout should be the same with the design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#43]
![untitled-1-newss01](https://cloud.githubusercontent.com/assets/13309730/13673068/7210f19c-e6fd-11e5-8988-68928206681e.png)

**Comment by euveng** [comment]
Will not fix for following reasons:

1. Featured image does not follow bootstrap grid so it became wider and higher than it should.
2. Post content line-height is currently minimal - if we further shorten it it will affect readability.
