### ISSUE TITLE
Home-Videos: Styling of the video container is not the same with the design, Also Icon is used different from the design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#44]
Displaying unnecessary black space

![untitled-1-home-video](https://cloud.githubusercontent.com/assets/13309730/13673236/324c1f36-e6fe-11e5-8647-ec9c7af99940.png)

**Comment by euveng** [comment]
Fixed unnecessary black space.
Will not fix the 'share' button - this is generated by Youtube by default.
