### ISSUE TITLE
Feedback page: Some of the fields are not implemented as per design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#50]
![untitled-100222](https://cloud.githubusercontent.com/assets/13309730/13675838/6c26dc86-e709-11e5-927d-7d6ced39fdf5.png)

**Comment by euveng** [comment]
Fixed. Due to using pseudo elements as the radio button which references the label tag, the radio button cannot be displayed at the 'other' input field. However the text field is fully functional.

**Comment by mahender-sowedane** [comment]
Still some of the fields aren't implemented as stated in design.

![untitled-feedback](https://cloud.githubusercontent.com/assets/13309730/13739241/0b9a5746-e9f0-11e5-8d0d-25a560c186f4.png)

**Comment by euveng** [comment]
Fixed.
