### ISSUE TITLE
Inner pages-Contact Us form: Title 'Us' breaks to the next line & form is too short on resolution browser reflow.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#53]
![2016-03-10_2159-1199](https://cloud.githubusercontent.com/assets/13309730/13676426/cbd74704-e70b-11e5-841f-e84f649042eb.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still re-produced on homepage banner form section on Ipod

![img_1408](https://cloud.githubusercontent.com/assets/13309730/13739047/c3a75d90-e9ee-11e5-85fd-23d8230037de.PNG)

**Comment by euveng** [comment]
Fixed.
