### ISSUE TITLE
General: All button sizes are not the same with the design, It should be consistent as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#55]
![untitled-1bb](https://cloud.githubusercontent.com/assets/13309730/13677011/4e2f8a16-e70e-11e5-87f6-16589f30a5e7.png)

**Comment by euveng** [comment]
Will not fix for reasons discussed before.

For height: difference of less than 10px are negligible.
For width: buttons do not follow bootstrap grid, but a uniform horizontal padding throughout the site.
