### ISSUE TITLE
Feedback page: When validating the fields it will destroy the alignment 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#57]
![img_1530](https://cloud.githubusercontent.com/assets/13309730/13743550/642ec56e-ea08-11e5-8beb-a956f2d20cd7.PNG)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still affected for 'submit' button, Previously button alignment is fine but now it's affected.

![feedback-02](https://cloud.githubusercontent.com/assets/13309730/13773475/61c4688a-eabf-11e5-8a04-33f08a7d237d.png)

**Comment by euveng** [comment]
Fixed.
