### ISSUE TITLE
Testimonials: There shouldn't be default no-image used for testimonial without image.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#6]
It should be implement as per scope.
For list layouts, NEVER use the default “no-image” if item has no image.
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/default-no-image

![2016-03-09_1539-scope](https://cloud.githubusercontent.com/assets/13309730/13631975/627b9976-e60d-11e5-8adf-cce0952125c3.png)

![2016-03-09_1538-testimonis](https://cloud.githubusercontent.com/assets/13309730/13631977/678c780e-e60d-11e5-9f17-94a071483dee.png)

**Comment by euveng** [comment]
Fixed.
