### ISSUE TITLE
Home - Client Testimonials: Post images are should be rounded corner as per design. Happens on Safari browser.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#60]
![untitled-1](https://cloud.githubusercontent.com/assets/13309730/13743927/be3d0b2c-ea0a-11e5-88e3-aef4bfcaa09f.png)

**Comment by euveng** [comment]
Tested on Safari on desktop and ipad and it looks fine. Can you always detail the steps to reproduce the issue?

![image](https://cloud.githubusercontent.com/assets/9030354/13766245/252068bc-ea9b-11e5-8042-64b4e5ffb0ec.png)

![img_0022](https://cloud.githubusercontent.com/assets/9030354/13766280/80308bec-ea9b-11e5-8d91-15dc4bbbaf43.PNG)

**Comment by mahender-sowedane** [comment]
After discussion with TL, we no longer need to test the safari browser on the desktop as it's been discontinued for updates
thanks!
