### ISSUE TITLE
Home-Welcome content: Welcome description unordered list item's are not styled as per design.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#61]
![untitled-1-homepage](https://cloud.githubusercontent.com/assets/13309730/13744081/a2b7e61e-ea0b-11e5-8086-c0ab493b4925.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Welcome description unordered list item's are not styled as per design.

![2016-04-04_1538](https://cloud.githubusercontent.com/assets/13309730/14244891/60e25348-fa7b-11e5-94dc-4c449a6a8a39.png)

**Comment by euveng** [comment]
Fixed
