### ISSUE TITLE
Home-Why Choose Wonder Walls?: Text is not aligned properly on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#62]
![img_1224](https://cloud.githubusercontent.com/assets/13309730/13744255/906ea85c-ea0c-11e5-8eb3-01ecb1657a31.PNG)

![screenshot_2016-03-14-15-02-20](https://cloud.githubusercontent.com/assets/13309730/13744267/9b4b180a-ea0c-11e5-8767-d09611bdcc5e.png)

**Comment by euveng** [comment]
Fixed with issue #61.

**Comment by mahender-sowedane** [comment]
Text is not aligned properly.

![2016-04-04_1529](https://cloud.githubusercontent.com/assets/13309730/14244787/a6ea3ece-fa7a-11e5-8a82-1728d684d6d7.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
List icon's should be vertically center aligned with text.

![issue03](https://cloud.githubusercontent.com/assets/13309730/14559075/f077819e-0323-11e6-9de4-d9fd50efdff2.png)

**Comment by euveng** [comment]
This is a minor issue and does not justify additional resource, will not fix.
