### ISSUE TITLE
Header section: Social links section should be vertically center aligned on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#63]
![img_1223](https://cloud.githubusercontent.com/assets/13309730/13744334/1b388a16-ea0d-11e5-89be-d271520db385.PNG)

![screenshot_2016-03-14-16-12-04](https://cloud.githubusercontent.com/assets/13309730/13744336/1b40331a-ea0d-11e5-8a4c-7aa96025f80d.png)

**Comment by euveng** [comment]
Fixed.
