### ISSUE TITLE
Contact Us page: Broken alignment for Contact us fileds on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#64]
![screenshot_2016-03-14-15-12-00](https://cloud.githubusercontent.com/assets/13309730/13744431/b521d740-ea0d-11e5-80f1-24cdacd527ff.png)

![img_1532](https://cloud.githubusercontent.com/assets/13309730/13744435/bca9a236-ea0d-11e5-86be-9abbda8f97f0.PNG)

**Comment by euveng** [comment]
Fixed.
