### ISSUE TITLE
Testimonials page: Post image should be vertically center aligned on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#66]
![untitled-2-testimoni](https://cloud.githubusercontent.com/assets/13309730/13745241/0a09ba8e-ea13-11e5-9846-77344c8c476b.png)

**Comment by euveng** [comment]
Vertically center aligned?

**Comment by mahender-sowedane** [comment]
After discussion with my TL, This should be an enhancement.

**Comment by euveng** [comment]
Fixed.
