### ISSUE TITLE
Header section: Font-size isn't set to 16px. Currently used font-size is 15px only.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#76]
Also font-family should be 'Lato Regular'.

![untitled-1-header](https://cloud.githubusercontent.com/assets/13309730/13778064/9e21254c-ead9-11e5-89ca-00234073141e.png)

**Comment by euveng** [comment]
Font size changed to 16px. 
Font-weight: normal is the equivalent of regular. Marking this as invalid.
