### ISSUE TITLE
Feedback page : Alignment is distorting on reflow

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#80]

**Comment by mahender-sowedane** [comment]
![feedback1](https://cloud.githubusercontent.com/assets/13309730/13980439/9ed0da10-f104-11e5-84b5-f91dc840b162.png)

**Comment by euveng** [comment]
Fixed.

**Comment by mahender-sowedane** [comment]
Still not fixed.

**Comment by euveng** [comment]
Fixed. There was an error in the previous update.
