### ISSUE TITLE
Feedback page : Maintain less gap between the fields and error message 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#81]
![feedback2](https://cloud.githubusercontent.com/assets/13309730/13981031/9eda1b5e-f107-11e5-8178-9ad1fae4576a.png)

**Comment by euveng** [comment]
I have made small adjustments to reduce the gap, but some gaps need to be maintained to keep the 'would you recommend us' and 'suggestions or comments' fields on the same line.
