### ISSUE TITLE
Feedback page : "How did you hear about us?" section is not implemented as per design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#82]
![2016-04-04_1019](https://cloud.githubusercontent.com/assets/13309730/14242755/60aaca7e-fa6f-11e5-909d-a2d8e2d690d7.png)

**Comment by euveng** [comment]
This is a limitation within Gravity form, it does not allow the 'other' field to have a label. Marking this as wontfix.
