### ISSUE TITLE
Installation page : Equal gap should be maintained between the gallery images

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#85]
Applicable for versatility page also.

![2016-04-06_1518](https://cloud.githubusercontent.com/assets/13309730/14313641/4df0d14c-fc10-11e5-8233-9e942cdf97e9.png)

![2016-04-06_1515](https://cloud.githubusercontent.com/assets/13309730/14313648/562343ea-fc10-11e5-996e-8ffb44b2d213.png)

**Comment by euveng** [comment]
Fixed
