### ISSUE TITLE
General pages : Pagination is not styled. It should follow the design

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#86]
![2016-04-06_1527](https://cloud.githubusercontent.com/assets/13309730/14313687/9d29f50e-fc10-11e5-82f5-cc7eee14431e.png)

**Comment by euveng** [comment]
This is the standard bootstrap output and we want to avoid changing the convention, so I will mark this as won't fix.

**Comment by euveng** [comment]
Sorry, exactly what is the issue?

**Comment by mahender-sowedane** [comment]
#40
