### ISSUE TITLE
Home page (Videos) : Video title layout is missing on small devices on portrait mode

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#91]
Video title is out of scope on Ipad and Ipad(mini) landscape mode
Devices : Ipad, Ipad(mini), Samsung E7 and Itouch

![2016-04-07_1028](https://cloud.githubusercontent.com/assets/13309730/14341308/4d708f8e-fcae-11e5-85d3-7493eb5d960f.png)

![2016-04-07_1028_001](https://cloud.githubusercontent.com/assets/13309730/14341311/50f63d20-fcae-11e5-9011-807465fc1355.png)

![2016-04-07_1033_001](https://cloud.githubusercontent.com/assets/13309730/14341314/5642d144-fcae-11e5-854e-144537e84189.png)

**Comment by euveng** [comment]
Sorry, I don't understand the issue.

**Comment by mahender-sowedane** [comment]
#44
