### ISSUE TITLE
FAQ : Alignment is not implemented properly on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#92]
Devices : Ipad, Ipad(mini), Samsung E7 and Itouch

![2016-04-07_1029](https://cloud.githubusercontent.com/assets/13309730/14341337/a0e483c8-fcae-11e5-8ae2-8622d3bec6fa.png)
![2016-04-07_1029_001](https://cloud.githubusercontent.com/assets/13309730/14341342/a6d71796-fcae-11e5-88c9-bd0544b97e24.png)
![2016-04-07_1034](https://cloud.githubusercontent.com/assets/13309730/14341344/abe6ca56-fcae-11e5-8cf2-1883ae4a16a7.png)

**Comment by euveng** [comment]
Fixed faq bullet points.
