### ISSUE TITLE
Contact us page : Fields alignment is distorting on devices

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#93]
Devices : Ipad, Ipad(mini), Samsung E7 and Itouch
![2016-04-07_1030](https://cloud.githubusercontent.com/assets/13309730/14341377/f18eaff6-fcae-11e5-8ed8-8c5688287998.png)
![2016-04-07_1035](https://cloud.githubusercontent.com/assets/13309730/14341381/f461da5a-fcae-11e5-97a2-ba01868ff365.png)

**Comment by euveng** [comment]
Fixed it, it must have been when we adjusted the alignment in the previous fix.
