### ISSUE TITLE
Contact us page : Fields are unable to click on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#95]
Name, Email, Site address and Email fields are unable to click

Devices : Ipad, Ipad(mini), Samsung E7 and Itouch
![2016-04-07_1035_001](https://cloud.githubusercontent.com/assets/13309730/14341506/da30fa3e-fcaf-11e5-9ad8-9ac29861c23e.png)

![2016-04-07_1031](https://cloud.githubusercontent.com/assets/13309730/14341510/de9390e6-fcaf-11e5-929a-a9026dd82420.png)

**Comment by euveng** [comment]
Fixed. It was an issue with the form field itself.
