### ISSUE TITLE
FAQ's page: W3C errors.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#97]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwonderwalls.stage.titanweb.com.au%2Ffaqs%2F

![2016-04-15_1611faq](https://cloud.githubusercontent.com/assets/13309730/14559331/9a9987e8-0325-11e6-8cca-cc4587bdecde.png)

**Comment by euveng** [comment]
There is nothing to be fixed. 
![image](https://cloud.githubusercontent.com/assets/9030354/14591540/ae8cd63e-0545-11e6-8379-64292017a629.png)

**Comment by mahender-sowedane** [comment]
I don't think so, when i'm testing i found this issue.
thanks!
