### ISSUE TITLE
News page-Mobile: There's no sufficient space between post title and post content on devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Wonderwalls#98]
And also browser reflow

![postnews01](https://cloud.githubusercontent.com/assets/13309730/14559483/b893c654-0326-11e6-82dc-2d2da6b0f451.png)

![issue00003](https://cloud.githubusercontent.com/assets/13309730/14559566/4c067436-0327-11e6-9c2c-5e56db913f27.png)
![issuee00](https://cloud.githubusercontent.com/assets/13309730/14559567/4c0c1b84-0327-11e6-9dc7-3da1f2d8b0c5.png)

**Comment by euveng** [comment]
Next time, please refer to design before flagging issues like these. 
![image](https://cloud.githubusercontent.com/assets/9030354/14591545/e04b088a-0545-11e6-949c-a4daf956e97b.png)
