### ISSUE TITLE
Titan Theme Options: Missing login logo.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Wonderwalls#99]
![image](https://cloud.githubusercontent.com/assets/13363508/14664544/9afd4904-06fe-11e6-9e0c-1371f07f31c0.png)

**Comment by euveng** [comment]
Fixed.

**Comment by maehtitan** [comment]
Logo URL is incorrect including the tool tip or logo title.
![image](https://cloud.githubusercontent.com/assets/13363508/14665297/ac7307d6-0704-11e6-938f-e61f24b0e707.png)

**Comment by euveng** [comment]
Is this a new standard? As far as I checked, all other Titan sites do not have this implemented.

**Comment by maehtitan** [comment]
It is now checked coz it is implemented in the new build. If it is in the old build we still ask the dev to implement it here.

**Comment by euveng** [comment]
I have discussed this with Jo and she says that she will send Roselie an email that this is optional.

**Comment by maehtitan** [comment]
If you don't want to fix this further please remove the login logo in implementation and revert back to the old one.

**Comment by euveng** [comment]
Fixed.
